name: Build & Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.1
      with:
        artifact_name: public
